### ISSUE TITLE
Repository clone error

### ISSUE THREAD

**Issue by vsadykov** [rice-solar-physics/IonPopSolver#1]
When I tried to copy the main repository recursively:
git clone --recursive https://github.com/rice-solar-physics/IonPopSolver.git
I have received the following output:
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
Clone of 'git@github.com:rice-solar-physics/Radiation_Model.git' into submodule path 'Radiation_Model' failed 
Finally I just decided to clone linked folders Radiation_model, rsp_toolkit and tinyxml2 in rsp separately conserving the tree structure.

**Comment by wtbarnes** [comment]
This should be fixed by my latest commit. The problem was that the `Radiation_Model` and `rsp_toolkit` submodules were added with ssh instead of https so the `.gitmodules` file was trying to clone them over ssh. 

Specifically,

```
[submodule "Radiation_Model"]
        path = Radiation_Model
        url = git@github.com:rice-solar-physics/Radiation_Model.git
[submodule "rsp_toolkit"]
        path = rsp_toolkit
        url = git@github.com:rice-solar-physics/rsp_toolkit.git
```

has been changed to

```
[submodule "Radiation_Model"]
        path = Radiation_Model
        url = https://github.com/rice-solar-physics/Radiation_Model.git
[submodule "rsp_toolkit"]
        path = rsp_toolkit
        url = https://github.com/rice-solar-physics/rsp_toolkit.git
```

 You should now be able to run

``` bash
git clone --recursive https://github.com/rice-solar-physics/IonPopSolver.git
```

and the two submodules should be pulled down without issue.

**Comment by vsadykov** [comment]
Thanks a lot! It works now!
