### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vsadykov** [rice-solar-physics/IonPopSolver#2]
I guess I have installed anaconda python, scons and program_options library correctly.
So, currently I can compile the code:

" scons
scons: Reading SConscript files ...
Using Linux compile options.
scons: done reading SConscript files.
scons: Building targets ...
g++ -o Radiation_Model/source/OpticallyThick/OpticallyThickIon.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include Radiation_Model/source/OpticallyThick/OpticallyThickIon.cpp
g++ -o Radiation_Model/source/element.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include Radiation_Model/source/element.cpp
g++ -o Radiation_Model/source/ionfrac.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include Radiation_Model/source/ionfrac.cpp
g++ -o Radiation_Model/source/radiation.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include Radiation_Model/source/radiation.cpp
g++ -o rsp_toolkit/source/xmlreader.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include rsp_toolkit/source/xmlreader.cpp
g++ -o rsp_toolkit/source/file.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include rsp_toolkit/source/file.cpp
g++ -o rsp_toolkit/source/fitpoly.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include rsp_toolkit/source/fitpoly.cpp
g++ -o rsp_toolkit/tinyxml2/tinyxml2.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include rsp_toolkit/tinyxml2/tinyxml2.cpp
g++ -o source/main.o -c -g -O3 -fno-stack-protector -Wall -I/usr/include source/main.cpp
g++ -o bin/IonPopSolver.run Radiation_Model/source/ionfrac.o Radiation_Model/source/radiation.o Radiation_Model/source/element.o Radiation_Model/source/OpticallyThick/OpticallyThickIon.o rsp_toolkit/source/xmlreader.o rsp_toolkit/source/file.o rsp_toolkit/source/fitpoly.o rsp_toolkit/tinyxml2/tinyxml2.o source/main.o -L/usr/lib/x86_64-linux-gnu -lboost_program_options
scons: done building targets.

However, when I tried to run the test:
"bin/IonPopSolver.run -Z 26 -f 9 -t 26 -I test/Tt_nt_1.txt -O test/test1.out -r test/radiation.example.cfg.xml"
I have received the segmentation fault error:
"Segmentation fault (core dumped)"

I did not trace this error. Possibly, you can tell some ideas what it can be?

**Comment by wtbarnes** [comment]
Have you installed the [apolloDB](https://github.com/rice-solar-physics/apolloDB) repository that contains all of the atomic data? If so, have you modified `test/radiation.example.cfg.xml` to point to the directory where you installed it? 

For example,

``` bash
cd /path/to/atomic/data/
git clone https://github.com/rice-solar-physics/apolloDB.git
```

Then in `test/radiation.example.cfg.xml`, you would set

``` xml
<atomicDB>/path/to/atomic/data/apolloDB/</atomicDB>
```

making sure to include the trailing slash.

**Comment by vsadykov** [comment]
Thank you a lot one more time!
This is the reason. The program works now.

**Comment by wtbarnes** [comment]
Great. This hopefully will get fixed so that a 'file not found' error will get thrown instead of a segmentation fault.
